### ISSUE TITLE
Certificate expired on Find site

### ISSUE THREAD

**Issue by TonyGravagno** [mre/vscode-snippet#131]
![211208152117](https://user-images.githubusercontent.com/499473/145307217-b5013b39-7f51-4969-88f3-7fb4be03abfe.png)

**Comment by mre** [comment]
That's an issue on the server-side. The old letsencrypt DST Root CA X3 cross-sign has expired. You can give the upstream issue a 👍 if you like. https://github.com/chubin/cheat.sh/issues/310

**Comment by mre** [comment]
@TonyGravagno can you try again now? The upstream issue seems to have been fixed.

**Comment by TonyGravagno** [comment]
I'm still getting the error with httpS, not with http, of course. From the Terminal I get a SSL connection and a response:  
`curl -v --ssl-reqd https://cht.sh/:help | more`

There must be a cache value that needs to be reset. I've exited VSCode and reopened the workspace. I'm completely unfamiliar with HTTP from VSCode, execution of a command-line, etc.

Thoughts?
(Please re-open until this is resolved, thanks.)

**Comment by mre** [comment]
Thanks for the feedback. Don't know of any certificate caching in VSCode. You could check inside the `~/.vscode` folder to be sure.

**Comment by mre** [comment]
Actually the settings are in `$HOME/Library/Application\ Support/Code/`, sorry.

**Comment by TonyGravagno** [comment]
No joy finding it yet (Windows). Looking. Thanks!

**Comment by TonyGravagno** [comment]
OK, no clue if this helps you or anyone. Will continue to look deeper as time permits - and it almost never does. :(

![image](https://user-images.githubusercontent.com/499473/147018812-0956617d-5e66-4307-bed4-a9c9075718e2.png)

**Comment by TonyGravagno** [comment]
I see in the code you a temporary response cache. I wonder if that's persisted in the workspace, and for how long:
https://github.com/mre/vscode-snippet/blob/18cfb370750d95102f01f20138038c5815652372/src/snippet.ts#L102

I'm also wondering if axios caches anything.

I've exhausted my time on this for now. HTH and thanks again.

**Comment by ssr-vpn** [comment]
There seems to be a solution. For this problem, I unchecked http.proxyStrictSSL and http.systemCertificates (search in settings), after, I can search for snippets, but I don't know if there is any security risk in http transmission by doing this

**Comment by TonyGravagno** [comment]
Confirming continued interest/support. Just haven't had time to re-check. Should be able to soon and will come back here to confirm. Thanks for your efforts!

**Comment by chubin** [comment]
Do you still have the problem with the upstream service? It should work well at the moment. Could you please verify?

**Comment by mre** [comment]
Works as expected for me. Closing this. Thanks @chubin. ❤️
